### ISSUE TITLE
Screenshots in README

### ISSUE THREAD

**Issue by VelocityRa** [Ralith/planetmap#1]
Hello, I think this project would benefit from showing it off via some screenshots of the demo application - you can't expect everyone coming across this to get the code and build it.

**Comment by Ralith** [comment]
This is absolutely justified; just haven't gotten to it. Don't hesitate to make a PR if you have some pretty ones!

**Comment by jomala** [comment]
They're all pretty! (This is exactly the project I've been meaning to do for a year, so I'm genuinely excited to come across this.) You could take these for instance.
![planetmap2](https://user-images.githubusercontent.com/3484507/65808207-c6e2ce80-e18a-11e9-9625-6ad85e5d54d5.png)
![planetmap1](https://user-images.githubusercontent.com/3484507/65808208-c6e2ce80-e18a-11e9-83e1-100f0863473d.png)
![planetmap3](https://user-images.githubusercontent.com/3484507/65808209-c77b6500-e18a-11e9-84d3-9efa44f2f902.png)

There seems to be [some disagreement](https://stackoverflow.com/questions/14494747/add-images-to-readme-md-on-github) over the best approach to adding screenshots to GitHub READMEs, but one approach would be to just copy those links in (and not close this README perhaps).

**Comment by Ralith** [comment]
Thanks! Let me know if you try to get it working in practice and have any questions (or pretty pictures!)
